[tool.ruff]
target-version = "py312"
line-length = 90

[tool.mypy]
python_version = "3.12"
warn_unused_configs = true
ignore_missing_imports = true
follow_imports = 'normal'
warn_redundant_casts = true
show_error_codes = true
