[tool.ruff]
target-version = "py312"
line-length = 90
lint.select = ["ALL"]
lint.ignore = [
    "D", # docstring
    "T201", # use of print
    "TD", # todo comments 
    "RET504", # unnecessary assignment
    "S101", # use of assert
    "PTH123", # use of open()
    "COM812", # always trailing comma
    "EM101", # raw string in exception
    "EM102", # f-string in exception
    "ERA001", # commented out code
    "TRY003", # raise vanilla args
]

[tool.ruff.lint.per-file-ignores]
"**.ipynb" = ["F404"]

[tool.mypy]
python_version = "3.12"
warn_unused_configs = true
ignore_missing_imports = true
follow_imports = 'normal'
warn_redundant_casts = true
show_error_codes = true
