[tool.ruff]
target-version = "py312"
line-length = 90
lint.select = ["ALL"]
lint.ignore = [
    "B018", # 'useless' expression
    "COM812", # always trailing comma
    "D", # docstring
    "EM101", # raw string in exception
    "EM102", # f-string in exception
    "ERA001", # commented out code
    "INP001", # implicit namespace package
    "PTH123", # use of open()
    "RET504", # unnecessary assignment
    "S101", # use of assert
    "T201", # use of print
    "TCH003", # stdlib type-checking imports
    "TD", # todo comments 
    "TRY003", # raise vanilla args
    "UP040", # type keyword is too new
]

[tool.ruff.lint.per-file-ignores]
"**.ipynb" = [
    "F404",
    "ANN001", # function argument annotations
    "ANN201", # annotations of public functions
    "ANN204", # annotations of __dunder__ methods
    ]

[tool.mypy]
python_version = "3.12"
warn_unused_configs = true
ignore_missing_imports = true
follow_imports = 'normal'
warn_redundant_casts = true
show_error_codes = true
